# Environment audit spec 
# Author: havembha@gmail.com,  2022/04/23
# Format
###
### you may use https://regex101.com/ to  test the regular expression definitions on log lines to parse
###
---
LogFile: JAEnvironment.log
Environment:
   Dev:
     # specify hostname in regular expression 
     HostName: ((...)(d)(...)([0-9][0-9]))|(LAPTOP-QOCNVF0T)
   Test:
     HostName: (...)(t)(...)([0-9][0-9])
   UAT:
     ## UAT environment uses the values defined under "All" environment for the variables DataPostIntervalInSec, DataCollectDurationInSec, DisableWarnings, VerifyCertificate
     HostName: (...)(u)(...)([0-9][0-9])
     WebServerURL: https://192.168.1.221:443/cgi-bin/JASaveStats.py
   Prod1:
     HostName: (...)(p1)(...)([0-9][0-9])
     WebServerURL: https://192.168.1.221:443/cgi-bin/JASaveStats.py
   Prod2:
     HostName: (...)(p2)(...)([0-9][0-9])
     WebServerURL: https://192.168.1.221:443/cgi-bin/JASaveStats.py
     
  ## Keep definition for 'All' environment at the end.
  ##  this is to ensure, Dev, Test, UAT, Prod etc environment specific values are seen/read first and 
  ##  assigned to variables. If a variable is not yet defined under Dev, Test.. like environment,
  ##  and that variable is defined under 'All', value under 'All' will be picked up
  ##  if variable is already defined under environment before, value under 'All' will be ignored.
   All:
     DisableWarnings: True
     ### do not verify web server certificate, defaults to True
     VerifyCertificate: False
     # post stats to below web server
     WebServerURL: https://192.168.1.221:443/cgi-bin/JASaveStats.py
     ### debug level 0, no debug, 1 to 4, 4 being max details
     DebugLevel: 0
Rules:
  variable: OSType = `uname`
  condition:
  OS:
    variable: OSVersion = `cat /etc/os-release |grep VERSION_ID |awk -F'=' '{print $2}'`