# Environment audit spec 
# Author: havembha@gmail.com,  2022/04/23
# Format
###
### you may use https://regex101.com/ to  test the regular expression definitions on log lines to parse
###
---
LogFilePath: ./
### platform name or application name covering all components covered by this environment spec
### have one environment spec file per platform or application to manage many platforms/ application of an organization
Platform:
  Name: Platform1

### Parameter name needs to be unique across all sections - OS, Component, and Environment
### Parameters can be defined under OS, Component or Environment.
### Parameter value can be redefined in other sections to override previous value.
### Parameters under OS will be read first, under Component next and under Environment last.
### While reading parameters under Component, if a value is present under specific component, 
###   it will be stored as latest desired value, overriding the value previously defined under OS
### While reading parameters under Environment, if a value is present under specific environment, 
###   it will be stored as latest desired value, overriding the value previously defined under OS or Component
### In all cases (OS, Component, Environment sections), value under 'All' will be stored 
###   if the value is not yet stored before in any prior section.
OS:
  SunOS:
    CommandCurl: /usr/bin/curl
    CommandWget: ../exe/wget
    CommandTelnet: ../exe/telnet
    ### add current working directory to path
    LD_LIBRARY_PATH: ./
    ### add current working directory to path
    PATH: ./
    CommandToGetOSType: uname
    CommandToGetOSVersion: cat /etc/os-release |grep VERSION_ID |awk -F'=' '{print $2}'
    ### use below command to change the file permission so that scripts can be executed after getting those from
    ###  WebServer using wget (wget does not retain original file permission on WebServer)
    CommandChmod: chmod 755 *.py *.bash *.ksh *.pl logfilter* 

  Linux:
    CommandTelnet: telnet
    ### use below command to change the file permission so that scripts can be executed after getting those from
    ###  WebServer using wget (wget does not retain original file permission on WebServer)
    CommandChmod: chmod 755 *.py *.bash *.ksh *.pl logfilter* 
  Windows:
    CommandTelnet: Test-NetConnection
    ### use below command to change the file permission so that scripts can be executed after getting those from
    ###  WebServer using wget (wget does not retain original file permission on WebServer)
    CommandChmod: ICACLS "yogasana manthra.pdf" /grant "users:(RWX)" /c

  All:
    ### default applies to all OS versions
    CommandCurl: curl
    ### rsync command to get artifacts from KITS to local host if rsync is to be used
    CommandRsync: 'rsync --exclude=".*.swp" --exclude="*/"  -avrL --progress --ignore-errors -e "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTime=10"'
    ### wget command used to get artifacts from KITS to local host
    CommandWget: wget

Component:
  ### using regular expression syntax, specify how to find component name of the application of platform
  ###  so that component specific variable values can be derived run time
  ### AppConfig naming convention - <SubsystemName><repositoryName><ComponentName>.yml[.<AppVersion>] where
  ###   <SubsystemName> - App for main application, DB for Database configurations, OS for OS configurations
  ###   <repositoryName>  - keep this same as platform name defined before for this environment
  ###   <ComponentName> - abbreviated component name
  ###   [.<AppVersion>] - this application version will be appended run time to derive the config file to be used
  ###           based on current application release installed on that host.
  ###        Command specified under CommandToGetAppVersion will be used run time to derive the application version
  ###        If command is not specified under CommandToGetAppVersion, or version returned is TBD, 
  ###           AppVersion will not be appended to derive full name.
  ### Operations specific configuration file has operation name prefixed to above AppConfig file name
  ### Example:
  ###    ConnAppPlatform1APP.yml, CertAppPlatform1APP.yml, HealAppPlatform1APP.yml, HealthAppPlatform1APP.yml 
  ###    ^^^^                     ^^^^                     ^^^^^                    ^^^^^^
  ###    LogStatsAppPlatform1APP.yml, OSStatsAppPlatform1APP.yml, StatsAppPlatform1APP.yml
  ###    ^^^^^^^^                     ^^^^^^^                     ^^^^^
  ###    TestAppPlatform1APP.yml, TaskAppPlatform1APP.yml
  ###    ^^^^                     ^^^^
  APPWin:
    ### if the current hostname match to below spec, it is considered of component type APP
    HostName: (LAPTOP-QOCNVF0T)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppAppsWindowsAPP.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: echo TBD
    ### datamask for this component
    DataMaskSpec: AppsWindows/DMAPP.yml
    ### fetch latest files from WebServer like KITSHostName1 + RepositoryCustom,
    ###   this component has component specific path on KITS host where artifacts are maintained
    RepositoryCustom: AppsWindows/

  APPLinux:
    ### if the current hostname match to below spec, it is considered of component type APP
    HostName: (...)(d|t|u|p)(app)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppAppsLinuxAPP.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: echo TBD
    ### datamask for this component
    DataMaskSpec: AppsLinux/DMAPP.yml
    ### fetch latest files from WebServer like KITSHostName1 + RepositoryCustom,
    ###   this component has component specific path on KITS host where artifacts are maintained
    RepositoryCustom: AppsLinux/

  CS:
    ### if the current hostname match to below spec, it is considered of component type APP
    HostName: (...)(d|t|u|p)(cs)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppAppsLinuxCS.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: cat ../conf/CS.version | sort | tail -1 | sed 's/\(.*\)\(CS\)-\(.*\)/\2/'
    ### datamask for this component
    DataMaskSpec: AppsLinux/DMCS.yml

  DB:
    ### if the current hostname match to below spec, it is considered of component type DB
    HostName: (...)(d|t|u|p)(db)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppPlatform1DB.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: cat ../conf/DB.version | sort | tail -1 | sed 's/\(.*\)\(DB\)-\(.*\)/\2/'
    ### datamask for this component
    DataMaskSpec: Platform1/DMDB.yml

  FS:
    ### if the current hostname match to below spec, it is considered of component type FS
    HostName: (...)(d|t|u|p)(fs)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppPlatform1FS.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: echo TBD
    ### datamask for this component
    DataMaskSpec: Platform1/DMFS.yml

  MGT:
    ### if the current hostname match to below spec, it is considered of component type MGT
    HostName: (...)(d|t|u|p)(mgt)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppPlatform1MGT.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: echo TBD
    ### datamask for this component
    DataMaskSpec: Platform1/DMMGT.yml

  WS:
    ### if the current hostname match to below spec, it is considered of component type WS
    HostName: (...)(d|t|u|p)(ws)
    ### start the app config name with platform name as prefix. this helps to associate the file easily to platform or application
    ###  when the file is sent via email or placed in some doc respository without any platform/application association
    AppConfig: AppPlatform1WS.yml
    ### number of characters to ignore while picking up partial hostname from current hostname and derive other hostnames
    ### of local site. This is used by connectivity test module.
    SitePrefixLength: 3
    ### command to get application version, this will be appended to form AppConfig file name if returned value is not TBD
    CommandToGetAppVersion: echo TBD
    ### datamask for this component
    DataMaskSpec: Platform1/DMWS.yml
    ### fetch latest files from WebServer like KITSHostName1 + RepositoryCustom,
    ###   this component has component specific path on KITS host where artifacts are maintained
    RepositoryCustom: Platform1/WS/

Environment:
   Dev:
     # specify hostname in regular expression 
     HostName: ((...)(d)(...)([0-9][0-9]))|(LAPTOP-QOCNVF0T)
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/
     OperationSync: 0.5
   Test:
     HostName: (...)(t)(...)([0-9][0-9])
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/
     OperationSync: 0.5
     ### keep  logs and result files for 7 days 
     FileRetencyDurationInDays: 7
   UAT:
     HostName: (...)(u)(...)([0-9][0-9])
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/
     ### will use the OperationSync value under ALL, thus, not specifying a value for UAT environment separately
   Prod1:
     HostName: (...)(p1)(...)([0-9][0-9])
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/
     OperationSync: 0
     ### keep  logs and result files for 14 days 
     FileRetencyDurationInDays: 14
     ###
   Prod2:
     HostName: (...)(p2)(...)([0-9][0-9])
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/
     OperationSync: 0
     ### keep  logs and result files for 14 days 
     FileRetencyDurationInDays: 14
     
   ## Keep definition for 'All' environment at the end.
   ##  this is to ensure, Dev, Test, UAT, Prod etc environment specific values are seen/read first and 
   ##  assigned to variables. If a variable is not yet defined under Dev, Test.. like environment,
   ##  and that variable is defined under 'All', value under 'All' will be picked up
   ##  if variable is already defined under environment before, value under 'All' will be ignored.
   All:
     ### Common code & config for all applications / platforms. 
     ### This word will be appended to KITSHostName to derive the URL to be used in wget command to 
     ### fetch latest files from WebServer like KITSHostName1 + RepositoryCommon
     RepositoryCommon: Common/
     ### Custom code & config repository for current application / platform or component of a platform
     ### This word will be appended to KITSHostName to derive the URL to be used in wget command to 
     ### fetch latest files from WebServer like KITSHostName1 + RepositoryCustom
     RepositoryCustom: Platform1/
     ### datamask spec at application level
     DataMaskSpec: Platform1/DMDefault.yml

     ### debug level 0, no debug, 1 to 4, 4 being max details
     DebugLevel: 3
     ### delta time for stats operation in min, process log lines with timestamp within below min from current time
     DeltaTimeForStatsInMin: 10

     ### diff options while comparing text files, if application is sensitive about space, DO NOT ignore space
     ###  -a - do text difference
     ###  -w - ignore all while space
     ###  -b - ignore amount of white space
     ###  -E - ignore tab
     ### resulting diff command with this option
     ###   diff diffOptions sourceFile referenceFile
     DiffOptions: -w
     ### disable cert warning while doing curl or wget with KITSHostName
     DisableWarnings: True
     ### by default, display cert due in message within 30 days of cert expiry when cert operation is run
     DueInDaysForCert: 30
     ### by default, display license due in message within 30 days of cert expiry when license operation is run
     DueInDaysForLicence: 30

     ### heal operation related definitions
     ### healInterval in seconds
     ###    take heal action within this interval with max action count not exceeding the HealCount specified for that command
     ###    for example, if healInterval is 7200 or 2 hours, HealCount = 3, process will be restarted 3 times
     ###    within 2 hours. 
     HealIntervalInSec: 7200
     ### HealAfterTime in seconds
     ###    heal action will be performed after this time is elapsed from detecting the condition first
     ###    this is to ensure normal stop/install/start operations does not trigger heal action
     ###    if a process is down for long time and HealStatusFileName is not defined/ not present, 
     ###      heal action will kick in
     HealAfterTimeInSec: 14400
     ### HealStatusFileName
     ###    If this file is present, heal action depends on value within this file.
     ###    Stopped - no action taken, system is under maintenance
     ###    Running - heal enabled, HealAfterTime is not used
     HealStatusFileName: ../bin/AppStatus.txt

     ### Define default operations intervals in hours
     ### 168 hours = 7 days
     ### 0.5 hours - use this value to run the operation every hour when the JaaduAudit is set to run every hour from crontab
     ###     specifying less than one hour so that any deviation in actual crontab execution will not impact.
     ### run certificate check
     OperationCert: 168
     ### run connectivity check
     OperationConn: 168
     ### while running connectivity check, whether to check OS connectivity 
     OperationConnOS: 168
     ### Compare application environment to default backup directory
     OperationCompare: 168
     ### perform heal operation, 0 is to disable by default
     OperationHeal: 0
     ### collect health
     OperationHealth: 0.5
     ### collect software inventory
     OperationInventory: 168
     ### collect license info
     OperationLicense: 168
     ### collect Application performance stats
     OperationPerfStatsApp: 0.5
     ### collect OS performance stats
     OperationPerfStatsOS: 0.5
     ### take backup of current application environment and OS environment
     OperationSave: 168
     ### parse logs, collect pass, fail, event count
     OperationStats: 0.5
     ### continuous deployment, get code & config from web server based on specified duration in number of hours
     ### sync is disabled by default
     OperationSync: 0
     ### run tasks, disabled by default
     OperationTask: 0
     ### run self-test
     OperationTest: 0.5
     ### upload collected data to WebServer
     OperationUpload: 0.5

     ###  this is to stagger the execution across many hosts at random to avoid any overload condition
     ###  value in seconds, defaults to 600
     RandomizationWindowInSec: 1
     
     ### rsync user name on KITS host to retrieve the artifacts from KITS to local host
     ### Comment this line or set to None if rsync is not used
     RsyncUserName: havembha

     ### default location to upload file on WebServer - local, replicate, support
     ###   local - file uploaded is kept on that web server only, not replicated to other WebServer, 
     ###       typically used to keep files of prod and non-prod seperate
     ###   replicate - replicate files to other WebServer or to WebServer in other environment like prod to non-prod
     ###         use replicate to place prod environment files to replicate areas so that users with non-prod access
     ###        can also access the prod environment files 
     ###   support - file uploaded is kept on that web server in a folder that can be accessed by support team
     ###       to download the file to user's host and process that file further 
     ###       support folder on webserver allows browsing capability and allows file download
     UploadLocation: local
     ### 
     ### do not verify web server certificate, defaults to True
     VerifyCertificate: False
     ### web server to pull the latest code & config from and to post the artifacts collected
     ###  can use single name if load balancer based FQDN is availabe
     KITSHostName1: https://192.168.1.169:443/
     KITSHostName2: https://192.168.1.169:443/

